### PR TITLE
assignment_01_6445

### PR DESCRIPTION
**Pull request by ChanandlerBond**

### CODE REVIEW

**Comment by ifarah** [comment]
@ChanandlerBond please add your name and last name to the file next time you submit! Thanks!

**Comment by ChanandlerBond** [comment]
> @ChanandlerBond please add your name and last name to the _file name_ next time you submit! Thanks!

Gotcha! I used the last 4 digits of my student number (6445) in this case.

**Comment by ifarah** [comment]
@ChanandlerBond It seems like your assignment was pushed into the root directory instead of the assignment_1 folder. Could you push it again and open a new PR so I can merge the pull request into the right folder?

**Comment by ChanandlerBond** [comment]
> @ChanandlerBond It seems like your assignment was pushed into the root directory instead of the assignment_1 folder. Could you push it again and open a new PR so I can merge the pull request into the right folder?

I just pushed the file again!

**Comment by ifarah** [comment]
> > @ChanandlerBond It seems like your assignment was pushed into the root directory instead of the assignment_1 folder. Could you push it again and open a new PR so I can merge the pull request into the right folder?
> 
> I just pushed the file again!

Looks good!

**Pull request merged**
